/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gradle.tutorial;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TestFunction {
    @Test void TestAdd() {
        Function f = new Function();
        assertEqual(f.add(1,2), 3);
    }
    @Test void TestSubtract() {
        Function f = new Function();
        assertEqual(f.subtract(3,2), 1);
    }
}
