/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gradle.tutorial;

import java.util.Scanner;

public class Demo {

    public static void main(String[] args) {
        Scanner key = new Scanner(System.in);
        Calculator c = new Calculator();
        Function f = new Function();
        System.out.println(c.getNum1());
        int num1 = key.nextInt();
        System.out.println(c.getNum2());
        int num2 = key.nextInt();
        System.out.println(c.selectFunction());
        int select = key.nextInt();
        int result = 0;
        switch(select)
        {
            case 1: result = f.subtract(num1, num2);
                    break;
            case 2: result = f.add(num1, num2);
                    break;
            case 3: result = f.multiply(num1, num2);
                    break;
            case 4: result = f.divide(num1, num2);
                    break;
        }
        System.out.println(c.getResult() + result);
    }
}
